git:
  depth: 1
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ruma"
    use_notice: true
script:
  - "docker version"
  - "docker-compose version"
  - "make ci"
services:
  - "docker"
sudo: "required"
