before_install:
  - "sudo add-apt-repository -y ppa:cjwatson/launchpad"
  - "sudo apt-get update"
  - "sudo apt-get -y install libsodium-dev"
cache: "cargo"
git:
  depth: 1
install:
  - "cargo install --force diesel_cli"
language: "rust"
notifications:
  email: false
  irc: "chat.freenode.net#ruma"
rust:
  - "nightly"
script:
  - "cargo build"
  - "make"
services:
  - "docker"
sudo: "required"
