[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A Matrix homeserver."
documentation = "http://ruma.github.io/ruma/ruma"
homepage = "https://github.com/ruma/ruma"
keywords = ["matrix", "matrix.org", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.1.0"

[dependencies]
bodyparser = "0.1.0"
clap = "1.5.5"
diesel = "0.5.0"
env_logger = "0.3.2"
hyper = "0.7.2"
iron = "0.2.6"
log = "0.3.5"
mount = "0.0.9"
persistent = "0.0.9"
r2d2 = "0.6.3"
r2d2-diesel = "0.5.0"
rand = "0.3.13"
router = "0.1.0"
rust-crypto = "0.2.34"
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"

[dependencies.diesel_codegen]
default-features = false
features = []
version = "0.5.0"
