[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A server for Matrix.org's client-server API."
documentation = "http://ruma.github.io/ruma/ruma"
homepage = "https://github.com/ruma/ruma"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.1.0"

[dependencies]
argon2rs = "0.2.1"
base64 = "0.1.1"
bodyparser = "0.3.0"
clap = "2.2.4"
diesel = "0.5.3"
env_logger = "0.3.2"
hyper = "0.8.0"
iron = "0.3.0"
log = "0.3.5"
mount = "0.1.0"
persistent = "0.1.0"
r2d2 = "0.6.4"
r2d2-diesel = "0.5.0"
rand = "0.3.14"
router = "0.1.1"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.0"

[dependencies.diesel_codegen]
default-features = false
features = ["nightly"]
version = "0.5.4"
