[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A server for Matrix.org's client-server API."
documentation = "http://ruma.github.io/ruma/ruma"
homepage = "https://github.com/ruma/ruma"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.1.0"

[dependencies]
argon2rs = "0.2.1"
base64 = "0.1.1"
bodyparser = "0.1.0"
clap = "1.5.5"
diesel = "0.5.0"
diesel_codegen = "0.5.0"
env_logger = "0.3.2"
hyper = "0.7.2"
iron = "0.2.6"
log = "0.3.5"
mount = "0.0.10"
persistent = "0.0.9"
r2d2 = "0.6.3"
r2d2-diesel = "0.5.0"
rand = "0.3.13"
router = "0.1.0"
serde = "0.6.14"
serde_json = "0.6.0"
serde_macros = "0.6.14"
