version: "2"
services:
  rust:
    image: "rumaio/ruma-dev@sha256:0eea3024c17d8b94b679e4cbf7ba6131ef21d322381458c4cf04e35337dd0c8c"
    links:
      - "postgres"
    volumes:
      - ".:/source"
      - "cargo_git:/root/.cargo/git"
      - "cargo_registry:/root/.cargo/registry"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=test"
volumes:
  cargo_git: {}
  cargo_registry: {}
