version: "2"
services:
  rust:
    image: "rumaio/ruma-dev@sha256:22ac646ba89de7020c4d612546ccd79b6090cbbce2bca5dd87790566cbd4685f"
    links:
      - "postgres"
    volumes:
      - ".:/source"
      - "cargo_git:/root/.cargo/git"
      - "cargo_registry:/root/.cargo/registry"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=test"
volumes:
  cargo_git: {}
  cargo_registry: {}
