version: "2"
services:
  rust:
    image: "rumaio/ruma-dev@sha256:901aa6288b88f0cf1a48ce99ead922165748ca0f0f4ffbe54a093f68f774d725"
    links:
      - "postgres"
    volumes:
      - ".:/source"
      - "cargo_git:/root/.cargo/git"
      - "cargo_registry:/root/.cargo/registry"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=test"
volumes:
  cargo_git: {}
  cargo_registry: {}
